const questions = [
  { q:"What does it mean that Rust is statically typed?", options:["Types are checked only after deployment","The compiler must know the type of every value at compile time","Variables cannot ever change value","Every type must be written manually"], answer:1, why:"Rust checks types at compile time, though it can often infer them." },
  { q:"Which group contains only scalar types?", options:["i32, f64, bool, char","tuple, array, String, Vec","i32, array, bool, tuple","char, tuple, f64, array"], answer:0, why:"Integers, floats, booleans, and chars are scalar types." },
  { q:"Which Rust type is unsigned?", options:["i32","f64","u64","char"], answer:2, why:"Unsigned integer types start with u, such as u64." },
  { q:"What does the `i` in `i32` mean?", options:["indexed","immutable","inferred only","integer with sign support"], answer:3, why:"i32 is a signed 32-bit integer." },
  { q:"What does the `u` in `u32` mean?", options:["Unicode","untyped","unsigned integer","unlimited size"], answer:2, why:"u32 can store only non-negative integer values." },
  { q:"Which type is Rust's default floating-point type?", options:["f16","f32","f64","float"], answer:2, why:"Rust defaults floating-point numbers to f64." },
  { q:"Which values can a bool hold?", options:["0 and 1 only","true and false","yes and no","any integer"], answer:1, why:"Rust booleans use true and false." },
  { q:"What is special about Rust's char type?", options:["It stores only ASCII","It is always a full string","It can only store numbers","It represents a Unicode scalar value"], answer:3, why:"Rust char supports Unicode scalar values like Ω or emojis if the font supports them." },
  { q:"Which example is a tuple?", options:["[1, 2, 3]","(500, 6.4, true)","{1, 2, 3}","<i32, bool>"], answer:1, why:"Tuples use parentheses and can mix types." },
  { q:"What is destructuring a tuple?", options:["Breaking a tuple into individual variables","Deleting a tuple from memory","Turning a tuple into an array","Making all tuple values mutable"], answer:0, why:"Destructuring assigns tuple elements into separate variables." },
  { q:"How do you access the first item of a tuple named `point`?", options:["point[0]","point.first","point.0","point::0"], answer:2, why:"Tuple fields are accessed with dot plus index, such as point.0." },
  { q:"Which example is an array?", options:["(1, 2, 3)","{1, 2, 3}","array(1, 2, 3)","[1, 2, 3]"], answer:3, why:"Arrays use square brackets." },
  { q:"What must be true about all elements in a Rust array?", options:["They must have the same type","They must all be strings","They must be mutable","They must be floating-point numbers"], answer:0, why:"Rust arrays contain elements of one type." },
  { q:"What does `[3; 5]` create?", options:["An array with values 3, 4, 5","An array of five 3 values","A tuple with two values","An integer range"], answer:1, why:"[value; count] repeats value count times." },
  { q:"How do you access the first element of an array named `numbers`?", options:["numbers.0","numbers::first","numbers[0]","numbers(0)"], answer:2, why:"Arrays use bracket indexing starting at zero." },
  { q:"Which statement about arrays is correct?", options:["Arrays can change length automatically","Arrays can mix any types","Arrays are always stored as text","Arrays have a fixed length"], answer:3, why:"Arrays in Rust have a fixed length." },
  { q:"When might you need a type annotation in Rust?", options:["When Rust cannot infer the intended type","Before every let statement","Only for booleans","Never, annotations are illegal"], answer:0, why:"Annotations are needed when inference is ambiguous." },
  { q:"Which is the best type for a number that should never be negative and can fit in 8 bits?", options:["i8","u8","f64","char"], answer:1, why:"u8 is an unsigned 8-bit integer." },
  { q:"What is the main difference between tuple and array?", options:["Tuples can mix types; arrays use one type","Arrays can mix types; tuples use one type","Tuples always grow; arrays cannot store numbers","There is no difference"], answer:0, why:"Tuples can group mixed types; arrays store same-type values." },
  { q:"Why are data types important before learning ownership?", options:["Data types replace functions","Ownership only works for f64","Rust has no compiler without arrays","Ownership depends on how values are stored and moved"], answer:3, why:"Understanding values and storage prepares you for ownership and moves." }
];

const state = { index: 0, answers: Array(questions.length).fill(null) };
const $ = id => document.getElementById(id);
const els = { start:$("startBtn"), reset:$("resetBtn"), prev:$("prevBtn"), next:$("nextBtn"), counter:$("questionCounter"), text:$("questionText"), options:$("options"), feedback:$("feedback"), fill:$("progressFill"), percent:$("progressPercent"), heroScore:$("heroScore"), heroStatus:$("heroStatus"), results:$("results"), scoreLine:$("scoreLine"), correct:$("correctMetric"), wrong:$("wrongMetric"), mastery:$("percentMetric"), review:$("reviewList") };
function formatCode(t){return t.replace(/(`[^`]+`)/g,m=>`<code>${m.slice(1,-1)}</code>`)}
function render(){const q=questions[state.index];const answered=state.answers.filter(a=>a!==null).length;const pct=Math.round(answered/questions.length*100);els.counter.textContent=`Question ${state.index+1} of ${questions.length}`;els.text.textContent=q.q;els.fill.style.width=`${pct}%`;document.querySelector('.progress-ring').style.background=`conic-gradient(var(--blue) ${pct*3.6}deg,#e2e8f0 0deg)`;els.percent.textContent=`${pct}%`;els.heroScore.textContent=`${answered} / ${questions.length}`;els.heroStatus.textContent=answered===questions.length?'All answered. Check your score.':`${questions.length-answered} questions left.`;els.options.innerHTML='';q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='option';b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-checked',state.answers[state.index]===i?'true':'false');b.innerHTML=`<span class="option__letter">${String.fromCharCode(65+i)}</span><span>${formatCode(option)}</span>`;b.onclick=()=>choose(i);const selected=state.answers[state.index];if(selected!==null){if(i===selected)b.classList.add('selected');if(i===q.answer)b.classList.add('correct');if(i===selected&&selected!==q.answer)b.classList.add('wrong')}els.options.appendChild(b)});feedback();els.prev.disabled=state.index===0;els.next.textContent=state.index===questions.length-1?'Show Results':'Next'}
function choose(i){state.answers[state.index]=i;render()}
function feedback(){const selected=state.answers[state.index];if(selected===null){els.feedback.className='feedback hidden';els.feedback.textContent='';return}const q=questions[state.index];const ok=selected===q.answer;els.feedback.className=`feedback ${ok?'good':'bad'}`;els.feedback.innerHTML=ok?`Correct. ${q.why}`:`Not yet. Correct answer: <strong>${String.fromCharCode(65+q.answer)}</strong>. ${q.why}`}
function showResults(){const correct=questions.reduce((sum,q,i)=>sum+(state.answers[i]===q.answer?1:0),0);const wrong=questions.length-correct;const pct=Math.round(correct/questions.length*100);els.correct.textContent=correct;els.wrong.textContent=wrong;els.mastery.textContent=`${pct}%`;els.scoreLine.textContent=pct>=85?'Strong work — your Rust type foundation is solid.':pct>=60?'Good progress — review the missed questions before the next lesson.':'Slow down and rerun the examples. Data types are the foundation.';els.review.innerHTML='';questions.forEach((q,i)=>{const d=document.createElement('div');d.className='review-item';d.innerHTML=`<strong>${i+1}. ${q.q}</strong><br><span>Answer ${String.fromCharCode(65+q.answer)} — ${q.options[q.answer]}</span>`;els.review.appendChild(d)});els.results.classList.remove('hidden');els.results.scrollIntoView({behavior:'smooth',block:'start'})}
els.start.onclick=()=>document.querySelector('.quiz-panel').scrollIntoView({behavior:'smooth',block:'start'});els.reset.onclick=()=>{state.index=0;state.answers=Array(questions.length).fill(null);els.results.classList.add('hidden');render()};els.prev.onclick=()=>{if(state.index>0){state.index--;render()}};els.next.onclick=()=>{if(state.index<questions.length-1){state.index++;render()}else showResults()};render();
