const questions = [
  { q:"What keyword starts a function definition in Rust?", options:["fn","function","def","func"], answer:0, why:"Rust function definitions start with `fn`." },
  { q:"In `fn print_line(width: usize)`, what is `width`?", options:["The return type","A parameter","The crate name","A compiler command"], answer:1, why:"`width` is the parameter name." },
  { q:"Why does Rust require parameter types in function definitions?", options:["To make every function async","To avoid using Cargo","To know exactly what input the function accepts","To force all values to be strings"], answer:2, why:"Rust is statically typed, so function inputs must have known types." },
  { q:"What does `-> usize` mean in a function signature?", options:["The function reads a file","The function prints text","The function is private","The function returns a usize value"], answer:3, why:"The arrow introduces the return type." },
  { q:"Which function has no explicit return value?", options:["fn print_line(width: usize) { println!(\"{}\", \"=\".repeat(width)); }","fn estimate_tokens(n: usize) -> usize { n / 4 }","fn build_default_instruction() -> String { String::from(\"Hi\") }","fn answer() -> i32 { 42 }"], answer:0, why:"A function with no `-> Type` returns unit `()`." },
  { q:"Which function correctly returns a number using the last expression?", options:["fn x() -> usize { 10; }","fn x() -> usize { 10 }","fn x() usize { 10 }","fn x() { -> 10 }"], answer:1, why:"The final expression without a semicolon becomes the return value." },
  { q:"What does a semicolon do to the final `10` in `fn x() -> usize { 10; }`?", options:["It makes the function faster","It imports usize","It turns the expression into a statement, so no value is returned","It makes 10 mutable"], answer:2, why:"A trailing semicolon prevents `10` from being returned as the final expression." },
  { q:"What compiler idea does `expected usize, found ()` usually suggest here?", options:["The file is missing Cargo.toml","The model is not installed","The variable is too large","The function promised a value but returned nothing"], answer:3, why:"`()`, called unit, means no meaningful value was returned." },
  { q:"Why does Lesson 03 avoid string references?", options:["To avoid teaching borrowing before learners are ready","Because Rust cannot use text","Because functions cannot receive text","Because Ollama forbids references"], answer:0, why:"The lesson keeps functions separate from borrowing so learners get one concept at a time." },
  { q:"Why is `estimate_tokens(character_count: usize)` useful in an AI-era course?", options:["It replaces the Rust compiler","It roughly checks prompt size before sending text to a model","It encrypts the prompt","It installs reqwest"], answer:1, why:"A rough token estimate helps students think about prompt/context size." },
  { q:"Which helper returns a reusable default instruction?", options:["print_line","rustc","build_default_instruction","main"], answer:2, why:"`build_default_instruction()` returns a reusable AI instruction as a `String`." },
  { q:"What is the best reason to keep functions small?", options:["Small functions never need types","Small functions always run on the GPU","Rust rejects long functions","Small functions are easier to understand, test, and reuse"], answer:3, why:"Small functions make programs clearer and easier to build gradually." },
  { q:"In `fn prompt_fits_context(estimated_tokens: usize, limit: usize) -> bool`, how many parameters are there?", options:["Two","Zero","Three","One"], answer:0, why:"The function receives `estimated_tokens` and `limit`." },
  { q:"What does `String::from(\"Answer clearly\")` create?", options:["A bool","A String","A usize","A char"], answer:1, why:"`String::from(...)` creates an owned `String`." },
  { q:"Which call matches `fn estimate_tokens(character_count: usize) -> usize` best?", options:["estimate_tokens()","estimate_tokens(\"hello\")","estimate_tokens(prompt_character_count)","estimate_tokens -> prompt_character_count"], answer:2, why:"The function expects a `usize`, and `prompt_character_count` is a `usize`." },
  { q:"What is the role of `main` in the runnable example?", options:["It is a quiz question","It is a JSON object","It is a CSS class","It is where the program starts and calls the helper functions"], answer:3, why:"Rust starts execution from `main`." },
  { q:"Which lesson pattern best matches Ayman's strategy here?", options:["Build a small useful example, run it, explain it, then improve it","Memorize every function rule before coding","Skip examples and read only compiler docs","Start with production agents immediately"], answer:0, why:"The course strategy is simple, impactful, gradual, and build-first." },
  { q:"When should real prompt text be passed into functions in this course?", options:["Never","After borrowing is introduced","Before variables","Only inside CSS"], answer:1, why:"Borrowing explains how to pass real text without unnecessary copying or moving." },
  { q:"Which statement about function return types is correct?", options:["All Rust functions must return String","Return types are written before `fn`","If a function returns a value, the signature can show it with `-> Type`","Return types are only checked at runtime"], answer:2, why:"Rust uses `-> Type` to declare an explicit return type." },
  { q:"What should you do when a function gets too complicated?", options:["Make every variable mutable","Delete all type annotations","Stop using Rust","Split the work into smaller named functions"], answer:3, why:"Breaking work into smaller functions keeps the code understandable." }
];

const state = { index: 0, answers: Array(questions.length).fill(null) };
const $ = id => document.getElementById(id);
const els = { start:$("startBtn"), reset:$("resetBtn"), prev:$("prevBtn"), next:$("nextBtn"), counter:$("questionCounter"), text:$("questionText"), options:$("options"), feedback:$("feedback"), fill:$("progressFill"), percent:$("progressPercent"), heroScore:$("heroScore"), heroStatus:$("heroStatus"), results:$("results"), scoreLine:$("scoreLine"), correct:$("correctMetric"), wrong:$("wrongMetric"), mastery:$("percentMetric"), review:$("reviewList") };
function formatCode(t){return t.replace(/(`[^`]+`)/g,m=>`<code>${m.slice(1,-1)}</code>`)}
function render(){const q=questions[state.index];const answered=state.answers.filter(a=>a!==null).length;const pct=Math.round(answered/questions.length*100);els.counter.textContent=`Question ${state.index+1} of ${questions.length}`;els.text.textContent=q.q;els.fill.style.width=`${pct}%`;document.querySelector('.progress-ring').style.background=`conic-gradient(var(--blue) ${pct*3.6}deg,#e2e8f0 0deg)`;els.percent.textContent=`${pct}%`;els.heroScore.textContent=`${answered} / ${questions.length}`;els.heroStatus.textContent=answered===questions.length?'All answered. Check your score.':`${questions.length-answered} questions left.`;els.options.innerHTML='';q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='option';b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-checked',state.answers[state.index]===i?'true':'false');b.innerHTML=`<span class="option__letter">${String.fromCharCode(65+i)}</span><span>${formatCode(option)}</span>`;b.onclick=()=>choose(i);const selected=state.answers[state.index];if(selected!==null){if(i===selected)b.classList.add('selected');if(i===q.answer)b.classList.add('correct');if(i===selected&&selected!==q.answer)b.classList.add('wrong')}els.options.appendChild(b)});feedback();els.prev.disabled=state.index===0;els.next.textContent=state.index===questions.length-1?'Show Results':'Next'}
function choose(i){state.answers[state.index]=i;render()}
function feedback(){const selected=state.answers[state.index];if(selected===null){els.feedback.className='feedback hidden';els.feedback.textContent='';return}const q=questions[state.index];const ok=selected===q.answer;els.feedback.className=`feedback ${ok?'good':'bad'}`;els.feedback.innerHTML=ok?`Correct. ${q.why}`:`Not yet. Correct answer: <strong>${String.fromCharCode(65+q.answer)}</strong>. ${q.why}`}
function showResults(){const correct=questions.reduce((sum,q,i)=>sum+(state.answers[i]===q.answer?1:0),0);const wrong=questions.length-correct;const pct=Math.round(correct/questions.length*100);els.correct.textContent=correct;els.wrong.textContent=wrong;els.mastery.textContent=`${pct}%`;els.scoreLine.textContent=pct>=85?'Strong work — you understand function shapes without mixing in borrowing too early.':pct>=60?'Good progress — review return values, parameters, and semicolons before moving on.':'Slow down and rerun the examples. Functions are how we start building real tools.';els.review.innerHTML='';questions.forEach((q,i)=>{const d=document.createElement('div');d.className='review-item';d.innerHTML=`<strong>${i+1}. ${q.q}</strong><br><span>Answer ${String.fromCharCode(65+q.answer)} — ${q.options[q.answer]}</span>`;els.review.appendChild(d)});els.results.classList.remove('hidden');els.results.scrollIntoView({behavior:'smooth',block:'start'})}
els.start.onclick=()=>document.querySelector('.quiz-panel').scrollIntoView({behavior:'smooth',block:'start'});els.reset.onclick=()=>{state.index=0;state.answers=Array(questions.length).fill(null);els.results.classList.add('hidden');render()};els.prev.onclick=()=>{if(state.index>0){state.index--;render()}};els.next.onclick=()=>{if(state.index<questions.length-1){state.index++;render()}else showResults()};render();
