const questions = [
  { q:"What is the simplest meaning of a variable in Rust?", options:["A name bound to a value","A file created by Cargo","A function that returns text","A type that can change at runtime"], answer:0, why:"A variable is a binding between a name and a value." },
  { q:"What must Rust know about every value at compile time?", options:["Its terminal color","Its type","Its future owner only","Its GitHub repository"], answer:1, why:"Rust is statically typed, so types are known at compile time." },
  { q:"What type does Rust usually infer for `let age = 30;`?", options:["u32","f64","i32","bool"], answer:2, why:"Rust's default integer type is i32." },
  { q:"What type does Rust usually infer for `let price = 19.99;`?", options:["i32","f32","u64","f64"], answer:3, why:"Rust's default floating-point type is f64." },
  { q:"Which line uses an explicit type annotation?", options:["let users: u32 = 120;","let users = 120;","users = 120;","let users == 120;"], answer:0, why:"The `: u32` part explicitly tells Rust the type." },
  { q:"Why might you write `let ratio: f32 = 0.75;`?", options:["To make it immutable","To choose f32 instead of the default f64","To make ratio a string","To avoid using let"], answer:1, why:"A type annotation lets you choose a specific type." },
  { q:"Why does `let guess = \"42\".parse().expect(...);` often need an annotation?", options:["Strings cannot be parsed in Rust","parse only returns bool","Rust does not know which target type you want","expect disables inference"], answer:2, why:"parse is generic; Rust needs a target type like u32 or i32." },
  { q:"Which is the correct way to parse into a `u32`?", options:["let guess = u32::parse(\"42\");","let guess parse u32 = \"42\";","let guess = \"42\":u32.parse();","let guess: u32 = \"42\".parse().expect(\"Not a number\");"], answer:3, why:"The variable annotation `: u32` tells parse the desired output type." },
  { q:"What does `mut` allow?", options:["Changing the variable's value","Changing the compiler version","Changing a variable into a function","Skipping type checks"], answer:0, why:"`mut` allows reassignment to a new value of the same type." },
  { q:"Which statement about `let mut count: i32 = 10;` is correct?", options:["count can become a string later","count can change value but stays i32","count is a constant","count cannot be printed"], answer:1, why:"Mutability changes values, not the variable's type." },
  { q:"Why does `let mut count = 10; count = \"ten\";` fail?", options:["Strings are not allowed in Rust","mut is only for constants","count was inferred as an integer, then assigned a string","println must come before assignment"], answer:2, why:"The variable keeps its inferred integer type; assigning a string is a type mismatch." },
  { q:"What is shadowing?", options:["Deleting a variable from memory","Making all variables mutable","Creating a new variable with the same name","Turning a number into a pointer"], answer:3, why:"Shadowing uses `let` again with the same name, creating a new binding." },
  { q:"Which example demonstrates shadowing?", options:["let x = 5; let x = x + 1;","let mut x = 5; x = 6;","const X: i32 = 5;","fn x() {}"], answer:0, why:"The second `let x` shadows the first x." },
  { q:"Why can shadowing change a variable's type?", options:["Because Rust becomes dynamically typed","Because the second `let` creates a new binding","Because mut changes types","Because strings and integers are the same"], answer:1, why:"Shadowing creates a new variable, so the new binding can have a different type." },
  { q:"In `let spaces = \"   \"; let spaces = spaces.len();`, what is the second `spaces`?", options:["A bool","A char","A usize number","A String allocation"], answer:2, why:"`len()` returns a `usize`, so the second binding is numeric." },
  { q:"Which declaration is a valid constant?", options:["const limit = 100;","let const LIMIT = 100;","mut const LIMIT: u32 = 100;","const LIMIT: u32 = 100;"], answer:3, why:"Constants use `const NAME: Type = value;` and require a type." },
  { q:"What naming style is conventional for Rust constants?", options:["SCREAMING_SNAKE_CASE","camelCase","lowercase only","kebab-case"], answer:0, why:"Rust constants conventionally use all caps with underscores." },
  { q:"What is the key difference between an immutable `let` variable and a `const`?", options:["const can use mut","const requires an explicit type and is never mutable","let variables cannot have types","const only stores strings"], answer:1, why:"Constants require type annotations and cannot be made mutable." },
  { q:"Which is the best beginner rule for annotations?", options:["Annotate every variable always","Never annotate anything","Use annotations when Rust cannot infer or when clarity matters","Only annotate booleans"], answer:2, why:"Rust inference keeps code clean, but annotations are valuable for clarity and ambiguous cases." },
  { q:"Which mental model is most accurate?", options:["Rust variables can become any type after `mut`","Rust has no type checking until runtime","Every Rust value has a type, and bindings make that type visible to the compiler","Shadowing is forbidden in Rust"], answer:3, why:"Rust is statically typed: every value has a compile-time type, and bindings help the compiler reason about it." }
];

const state = { index: 0, answers: Array(questions.length).fill(null) };
const $ = id => document.getElementById(id);
const els = { start:$("startBtn"), reset:$("resetBtn"), prev:$("prevBtn"), next:$("nextBtn"), counter:$("questionCounter"), text:$("questionText"), options:$("options"), feedback:$("feedback"), fill:$("progressFill"), percent:$("progressPercent"), heroScore:$("heroScore"), heroStatus:$("heroStatus"), results:$("results"), scoreLine:$("scoreLine"), correct:$("correctMetric"), wrong:$("wrongMetric"), mastery:$("percentMetric"), review:$("reviewList") };
function formatCode(t){return t.replace(/(`[^`]+`)/g,m=>`<code>${m.slice(1,-1)}</code>`)}
function render(){const q=questions[state.index];const answered=state.answers.filter(a=>a!==null).length;const pct=Math.round(answered/questions.length*100);els.counter.textContent=`Question ${state.index+1} of ${questions.length}`;els.text.textContent=q.q;els.fill.style.width=`${pct}%`;document.querySelector('.progress-ring').style.background=`conic-gradient(var(--blue) ${pct*3.6}deg,#e2e8f0 0deg)`;els.percent.textContent=`${pct}%`;els.heroScore.textContent=`${answered} / ${questions.length}`;els.heroStatus.textContent=answered===questions.length?'All answered. Check your score.':`${questions.length-answered} questions left.`;els.options.innerHTML='';q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='option';b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-checked',state.answers[state.index]===i?'true':'false');b.innerHTML=`<span class="option__letter">${String.fromCharCode(65+i)}</span><span>${formatCode(option)}</span>`;b.onclick=()=>choose(i);const selected=state.answers[state.index];if(selected!==null){if(i===selected)b.classList.add('selected');if(i===q.answer)b.classList.add('correct');if(i===selected&&selected!==q.answer)b.classList.add('wrong')}els.options.appendChild(b)});feedback();els.prev.disabled=state.index===0;els.next.textContent=state.index===questions.length-1?'Show Results':'Next'}
function choose(i){state.answers[state.index]=i;render()}
function feedback(){const selected=state.answers[state.index];if(selected===null){els.feedback.className='feedback hidden';els.feedback.textContent='';return}const q=questions[state.index];const ok=selected===q.answer;els.feedback.className=`feedback ${ok?'good':'bad'}`;els.feedback.innerHTML=ok?`Correct. ${q.why}`:`Not yet. Correct answer: <strong>${String.fromCharCode(65+q.answer)}</strong>. ${q.why}`}
function showResults(){const correct=questions.reduce((sum,q,i)=>sum+(state.answers[i]===q.answer?1:0),0);const wrong=questions.length-correct;const pct=Math.round(correct/questions.length*100);els.correct.textContent=correct;els.wrong.textContent=wrong;els.mastery.textContent=`${pct}%`;els.scoreLine.textContent=pct>=85?'Strong work — you understand how Rust connects variables and types.':pct>=60?'Good progress — review mutability, annotations, and shadowing before moving on.':'Slow down and rerun the examples. Variable types are a foundation skill.';els.review.innerHTML='';questions.forEach((q,i)=>{const d=document.createElement('div');d.className='review-item';d.innerHTML=`<strong>${i+1}. ${q.q}</strong><br><span>Answer ${String.fromCharCode(65+q.answer)} — ${q.options[q.answer]}</span>`;els.review.appendChild(d)});els.results.classList.remove('hidden');els.results.scrollIntoView({behavior:'smooth',block:'start'})}
els.start.onclick=()=>document.querySelector('.quiz-panel').scrollIntoView({behavior:'smooth',block:'start'});els.reset.onclick=()=>{state.index=0;state.answers=Array(questions.length).fill(null);els.results.classList.add('hidden');render()};els.prev.onclick=()=>{if(state.index>0){state.index--;render()}};els.next.onclick=()=>{if(state.index<questions.length-1){state.index++;render()}else showResults()};render();
