const questions = [
  { q:"What is the official tool normally used to install Rust?", options:["rustup","npm","pip","brew only"], answer:0, why:"The official Rust installer is rustup. It installs and manages Rust toolchains." },
  { q:"Where does a basic Rust program start running?", options:["start()","fn main()","run()","init()"], answer:1, why:"Rust starts execution in the main function: fn main() { ... }." },
  { q:"Which line creates a variable named x with the value 10?", options:["x := 10;","var x = 10;","let x = 10;","x = let 10;"], answer:2, why:"Rust uses let to bind a value to a variable name." },
  { q:"Which print statement correctly prints x using Rust's captured format syntax?", options:["println!({x});","print(x);","println!(x);","println!(\"{x}\");"], answer:3, why:"println! needs a format string. \"{x}\" tells Rust to print the variable x." },
  { q:"What is true about variables created with let by default?", options:["They are immutable","They are always global","They are deleted instantly","They must be strings"], answer:0, why:"Rust variables are immutable by default unless you write mut." },
  { q:"Why does this fail: let x = 10; x = 5; ?", options:["5 is not an integer","x was not declared as mutable","println! is missing","Rust cannot store 10"], answer:1, why:"The variable x is immutable, so assigning a new value to it is not allowed." },
  { q:"How do you declare x if you plan to change it later?", options:["let change x = 10;","mutable x = 10;","let mut x = 10;","var mut x = 10;"], answer:2, why:"Use let mut x = 10; when the variable should be allowed to change." },
  { q:"After let mut x = 10;, which line is allowed?", options:["let x mut 5;","x := 5;","change x to 5;","x = 5;"], answer:3, why:"A mutable variable can receive a new value using x = 5;." },
  { q:"What happens here for integers: let x = 10; let y = x; ?", options:["The value 10 is copied into y","x becomes invalid","y becomes a string","The program must use mut"], answer:0, why:"Simple integer values implement Copy, so both x and y can be used." },
  { q:"What should this print: let x = 10; let y = x; println!(\"{x} {y}\"); ?", options:["only y","10 10","compiler error because x moved","0 10"], answer:1, why:"For integers, y gets a copy of x, so both values are 10." },
  { q:"Which command compiles a single Rust file named main.rs?", options:["cargo main.rs","python main.rs","rustc main.rs","compile rust main.rs"], answer:2, why:"rustc main.rs compiles a single Rust source file." },
  { q:"What is the best beginner mindset for mutability in Rust?", options:["Make every variable mutable","Avoid variables completely","Use mut to make printing work","Use mut only when the value really needs to change"], answer:3, why:"Declare mut intentionally only when the variable needs to change; immutability is the safe default." }
];

const state = { index: 0, answers: Array(questions.length).fill(null) };
const $ = id => document.getElementById(id);
const els = { start:$("startBtn"), reset:$("resetBtn"), prev:$("prevBtn"), next:$("nextBtn"), counter:$("questionCounter"), text:$("questionText"), options:$("options"), feedback:$("feedback"), fill:$("progressFill"), percent:$("progressPercent"), heroScore:$("heroScore"), heroStatus:$("heroStatus"), results:$("results"), scoreLine:$("scoreLine"), correct:$("correctMetric"), wrong:$("wrongMetric"), mastery:$("percentMetric"), review:$("reviewList") };
function formatCode(t){return t.replace(/(`[^`]+`)/g,m=>`<code>${m.slice(1,-1)}</code>`)}
function render(){const q=questions[state.index];const answered=state.answers.filter(a=>a!==null).length;const pct=Math.round(answered/questions.length*100);els.counter.textContent=`Question ${state.index+1} of ${questions.length}`;els.text.textContent=q.q;els.fill.style.width=`${pct}%`;document.querySelector('.progress-ring').style.background=`conic-gradient(var(--blue) ${pct*3.6}deg,#e2e8f0 0deg)`;els.percent.textContent=`${pct}%`;els.heroScore.textContent=`${answered} / ${questions.length}`;els.heroStatus.textContent=answered===questions.length?'All answered. Check your score.':`${questions.length-answered} questions left.`;els.options.innerHTML='';q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='option';b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-checked',state.answers[state.index]===i?'true':'false');b.innerHTML=`<span class="option__letter">${String.fromCharCode(65+i)}</span><span>${formatCode(option)}</span>`;b.onclick=()=>choose(i);const selected=state.answers[state.index];if(selected!==null){if(i===selected)b.classList.add('selected');if(i===q.answer)b.classList.add('correct');if(i===selected&&selected!==q.answer)b.classList.add('wrong')}els.options.appendChild(b)});feedback();els.prev.disabled=state.index===0;els.next.textContent=state.index===questions.length-1?'Show Results':'Next'}
function choose(i){state.answers[state.index]=i;render()}
function feedback(){const selected=state.answers[state.index];if(selected===null){els.feedback.className='feedback hidden';els.feedback.textContent='';return}const q=questions[state.index];const ok=selected===q.answer;els.feedback.className=`feedback ${ok?'good':'bad'}`;els.feedback.innerHTML=ok?`Correct. ${q.why}`:`Not yet. Correct answer: <strong>${String.fromCharCode(65+q.answer)}</strong>. ${q.why}`}
function showResults(){const correct=questions.reduce((sum,q,i)=>sum+(state.answers[i]===q.answer?1:0),0);const wrong=questions.length-correct;const pct=Math.round(correct/questions.length*100);els.correct.textContent=correct;els.wrong.textContent=wrong;els.mastery.textContent=`${pct}%`;els.scoreLine.textContent=pct>=85?'Strong start — you understand the first Rust rules.':pct>=60?'Good progress — rerun the examples and review mutability.':'Slow down and type the examples yourself. Lesson 00 is the foundation.';els.review.innerHTML='';questions.forEach((q,i)=>{const d=document.createElement('div');d.className='review-item';d.innerHTML=`<strong>${i+1}. ${q.q}</strong><br><span>Answer ${String.fromCharCode(65+q.answer)} — ${q.options[q.answer]}</span>`;els.review.appendChild(d)});els.results.classList.remove('hidden');els.results.scrollIntoView({behavior:'smooth',block:'start'})}
els.start.onclick=()=>document.querySelector('.quiz-panel').scrollIntoView({behavior:'smooth',block:'start'});els.reset.onclick=()=>{state.index=0;state.answers=Array(questions.length).fill(null);els.results.classList.add('hidden');render()};els.prev.onclick=()=>{if(state.index>0){state.index--;render()}};els.next.onclick=()=>{if(state.index<questions.length-1){state.index++;render()}else showResults()};render();
